spring.application.name=Separation Worker

spring.datasource.url=${POSTGRESQL_SERVER_URL}
spring.datasource.username=${POSTGRESQL_ROOT_USERNAME}
spring.datasource.password=${POSTGRESQL_ROOT_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.config.import=optional:file:./.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest