spring.application.name=backend-sound-flow

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

google.client.id=${GOOGLE_CLIENT_ID}
google.client.secret=${GOOGLE_CLIENT_SECRET}

spring.datasource.url=${POSTGRESQL_SERVER_URL}
spring.datasource.username=${POSTGRESQL_ROOT_USERNAME}
spring.datasource.password=${POSTGRESQL_ROOT_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.config.import=optional:file:./.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

authorization.token.header.name=Authorization
authorization.token.header.prefix=Bearer 
authorization.token.secret=${JWT_TOKEN_SECRET}
# 10 hours
authorization.token.expiration-time=36000000
# 30 days
authorization.refresh-token.expiration-time=2592000000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nutritivnaz@gmail.com
spring.mail.password=${EMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

